<a href="https://colab.research.google.com/github/Deepali9894/SD_deepali_036/blob/main/library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
l = [1,2,3,4]

In [ ]:
ar = np.array(l)

In [ ]:
type(l)

list

In [ ]:
ar

array([1, 2, 3, 4])

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
np.array([[1,2] ,[3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
np .asarray(l)

array([1, 2, 3, 4])

In [ ]:
a = [2,3,4]

In [ ]:
np.asanyarray(a)

array([2, 3, 4])

In [ ]:
b = np.matrix(l)

In [ ]:
b

matrix([[1, 2, 3, 4]])

In [ ]:
 s = "deeps"

In [ ]:
s[-1::-5]

's'

In [ ]:
s[-1::-4]

'sd'